stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:lts
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - test/deploy

deploy:
  stage: deploy
  image: alpine
  before_script:
    - mkdir -p ~/.ssh
    - apk add --no-cache openssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - touch ~/.ssh/known_hosts
    - ssh-keyscan kdt-pt-1-pj-2-team02.elicecoding.com >> ~/.ssh/known_hosts
  script:
    - apk add --no-cache rsync openssh
    - rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./dist/ kdt@kdt-pt-1-pj-2-team02.elicecoding.com:/var/www/html/
  only:
    - test/deploy
