stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:lts
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - test/deploy

deploy:
  stage: deploy
  image: alpine
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - touch ~/.ssh/known_hosts
    - ssh-keyscan 34.22.99.12 >> ~/.ssh/known_hosts
  script:
    - apk add rsync openssh
    - rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./dist/ kdt@34.22.99.12:/var/www/html/
  only:
    - test/deploy
